services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/flightplanner
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
