spring.application.name=flightplanner
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.liquibase.change-log=db/changelog/changelog-master.xml
spring.datasource.username=postgres
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver
